apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      initContainers:
        - name: init-db  # 🏗️ Este contenedor inicializa el archivo en el volumen
          image: mramoscli/laravel-k8s  # Usamos tu propia imagen
          command: ['sh', '-c', 'cp /var/www/html/database/database.sqlite /mnt/database/database.sqlite']
          volumeMounts:
            - name: sqlite-volume
              mountPath: /mnt/database
      containers:
        - name: laravel
          image: mramoscli/laravel-k8s
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret
          volumeMounts:
            - name: sqlite-volume
              mountPath: /var/www/html/database
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: laravel-sqlite-pvc
