apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: mramoscli/laravel-k8s          # ← tu nueva imagen
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret
